---

services:

  database:
    container_name: database
    hostname: database
    image: postgres:12
    environment:
    - TZ=America/New_York
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 3

  zookeeper1:
    image: zookeeper:3.5
    container_name: zookeeper1
    hostname: zookeeper1
    environment:
    - TZ=America/New_York
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper1:2888:3888;2181
    - ZOO_STANDALONE_ENABLED=true
    - ZOO_4LW_COMMANDS_WHITELIST=*
    healthcheck:
      test: echo stat | nc zookeeper1 2181
      interval: 30s
      timeout: 5s
      retries: 3

  kafka1:
    image: bitnami/kafka:2.8.1
    container_name: kafka1
    hostname: kafka1
    depends_on:
      zookeeper1:
        condition: service_healthy
    ports:
    - 9094:9094
    environment:
    - TZ=America/New_York
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_BROKER_ID=1
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://:9092,EXTERNAL://${EXTERNAL_IP:-192.168.0.40}:9094
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181/kafka
    - KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000
    - KAFKA_CFG_NUM_PARTITIONS=4
    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
    - KAFKA_CFG_CONTROLLED_SHUTDOWN_ENABLE=true
    - KAFKA_HEAP_OPTS=-Xmx${KAFKA_HEAP:-2g} -Xms${KAFKA_HEAP:-2g} -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=kafka
    - JMX_PORT=9999
    healthcheck:
      test: JMX_PORT= kafka-topics.sh --list --bootstrap-server kafka1:9092
      interval: 30s
      timeout: 5s
      retries: 3

  manager:
    image: hlebalbau/kafka-manager:stable
    container_name: manager
    hostname: manager
    depends_on:
      zookeeper1:
        condition: service_healthy
    ports:
    - 9000:9000 
    environment:
    - TZ=America/New_York
    - ZK_HOSTS=zookeeper1:2181
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9000 || exit 1
      interval: 1m
      timeout: 5s
      retries: 3

  grpc1:
    build: ..
    container_name: grpc1
    hostname: grpc1
    depends_on:
      kafka1:
        condition: service_healthy
    ports:
    - 2112:2112
    - 8990:8990
    environment:
    - TZ=America/New_York
    - BOOTSTRAP_SERVER=kafka1:9092
    - LOG_LEVEL=debug
    healthcheck:
      test: /bin/grpc_health_probe -addr ':8990' -rpc-timeout 2s
      interval: 30s
      timeout: 5s
      retries: 3

  opennms:
    image: opennms/horizon:29.0.0
    container_name: opennms
    hostname: opennms
    depends_on:
      database:
        condition: service_healthy
      kafka1:
        condition: service_healthy
    command: [ -s ]
    ports:
    - 8980:8980
    - 8101:8101
    volumes:
    - ./opennms-overlay:/opt/opennms-overlay
    environment:
    - TZ=America/New_York
    - POSTGRES_HOST=database
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - JAVA_OPTS=-Xms${OPENNMS_HEAP:-4g} -Xmx${OPENNMS_HEAP:-4g} -XX:+AlwaysPreTouch -XX:+UseStringDeduplication
    healthcheck:
      test: curl -f -I http://localhost:8980/opennms/login.jsp
      interval: 1m
      timeout: 5s
      retries: 3

  minion1:
    container_name: minion1
    hostname: minion1
    image: opennms/minion:29.0.0
    depends_on:
      grpc1:
        condition: service_healthy
      opennms:
        condition: service_healthy
    command: [ -c ]
    volumes:
    - ./minion1.yaml:/opt/minion/minion-config.yaml
    environment:
    - TZ=America/New_York
    - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+UseG1GC -XX:+UseStringDeduplication
    healthcheck:
      test: /health.sh
      interval: 1m
      timeout: 5s
      retries: 3

  minion2:
    container_name: minion2
    hostname: minion2
    image: opennms/minion:29.0.0
    depends_on:
      grpc1:
        condition: service_healthy
      opennms:
        condition: service_healthy
    command: [ -c ]
    volumes:
    - ./minion2.yaml:/opt/minion/minion-config.yaml
    environment:
    - TZ=America/New_York
    - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+UseG1GC -XX:+UseStringDeduplication
    healthcheck:
      test: /health.sh
      interval: 1m
      timeout: 5s
      retries: 3

  minion3:
    container_name: minion3
    hostname: minion3
    image: opennms/minion:29.0.0
    depends_on:
      grpc1:
        condition: service_healthy
      opennms:
        condition: service_healthy
    command: [ -c ]
    volumes:
    - ./minion3.yaml:/opt/minion/minion-config.yaml
    environment:
    - TZ=America/New_York
    - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+UseG1GC -XX:+UseStringDeduplication
    healthcheck:
      test: /health.sh
      interval: 1m
      timeout: 5s
      retries: 3
